site_name: Galileo Protect

nav:
  - Galileo Protect Reference: index.md
  - Galileo Docs: https://docs.rungalileo.io/

theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.top
    - toc.integrate
  palette:
    primary: deep purple
    accent: purple
copyright: Copyright &copy; 2024 Galileo Technologies, Inc.
remote_branch: docs
extra:
  generator: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
            show_source: false
            preload_modules:
              - galileo_core
            filters: ["!__version__"]
            members: true
            members_order: source
            docstring_style: "numpy"
            docstring_section_style: "list"
            show_signature_annotations: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            unwrap_annotated: true
            show_if_no_docstring: true
            load_external_modules: true
            merge_init_into_class: true
            separate_signature: true
            extensions:
              - griffe_typingdoc
              - griffe_fieldz: { include_inherited: true }
