name: Publish Docs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Package Release"]
    types:
      - completed

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==${{ vars.POETRY_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"

      - name: Build Docs
        # Install all dependencies so that the docs can use the function and type signatures.
        run: |
          pipx install invoke
          poetry install --all-extras --without test,dev
          invoke docs-build

      - name: Publish Docs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
